### ISSUE TITLE
Very nice introduction!

### ISSUE THREAD

**Issue by gabyx** [ldionne/dyno#27]
:-) Very nice readme! Carry on the good work :).

I am very curious to see more interesting documentation in the readme :-). One really has to read the introduction two times :-) to wrap it into ones head  :-)!, nevertheless it is well written and makes superb analogies to the standard (unflexible ...) way of doing it.

**Comment by ldionne** [comment]
Thanks a lot for the kind words! If there is anything you think should be clarified in the README, please feel free to open an issue and we can discuss! This project has been sleeping a bit, but I do intend to bring it to a full quality library as time permits.
