### ISSUE TITLE
poly is 24 bytes instead of 16 bytes

### ISSUE THREAD

**Issue by ldionne** [ldionne/dyno#33]
Apparently, `hana::map` has a non-zero size and that causes `poly` to have a larger size than it should.

**Comment by ricejasonf** [comment]
Is the map always stateless and default constructible?

**Comment by ldionne** [comment]
I have no idea, I just took that note after someone mentioned this to me after my talk. I need to dive into this.

**Comment by ldionne** [comment]
> Is the map always stateless and default constructible?

No, it's the map in the vtable. The problem is that when we create a vtable from the vtable policy, we fold starting from an empty `local_vtable` and joining them with a `joined_vtable`. Since we don't do EBO all the way down, `joined_vtable` has two subobjects, one of which is empty (1 byte) and the other one is a pointer. The 1 byte object ends up with 7 bytes of padding due to the overall alignment of the structure. So that's `8 + 8 = 16` in the VTable, plus 8 for the storage in the poly. That's our 24 bytes.
