### ISSUE TITLE
Please create a C++20 proposal

### ISSUE THREAD

**Issue by jwaterloo** [ldionne/dyno#47]
Please create a C++20 proposal. I consider this as fundamental to developing as function_ref proposal and non member pointers. ... Possibly a simpler version just 2 pointers, no object storage or vtable storage customization. ... Really don't want to have to wait til 2023 when we get static reflection with injection to be able to make a library only version when this really could come sooner with language support.

**Comment by ldionne** [comment]
I do indeed plan to explore a language level approach for this. This would probably be something similar to coroutines, which is a language level feature backed by library customization points. But this will certainly not be for C++20, because we have a lot on our plate already.
