### ISSUE TITLE
Allow querying whether a type models a concept

### ISSUE THREAD

**Issue by ldionne** [ldionne/dyno#5]
Something like `te::models<Concept, T>` would be neat. That would require getting the concept map and checking whether all the methods are fulfilled.

**Comment by SuperV1234** [comment]
Is this basically asking to refactor and expose

```cpp
constexpr bool all_functions_satisfied = decltype(boost::hana::is_subset(
      boost::hana::keys(Concept::all_clauses()),
      boost::hana::keys(merged)
    ))::value;
```

from [`concept_map.hpp:240`](https://github.com/ldionne/te/blob/master/include/te/concept_map.hpp#L240-L243)?

**Comment by ldionne** [comment]
Yes, pretty much. I still need to figure out how I want to tie this to the rest of the library from a usage perspective.
